### ISSUE TITLE
closed when switching to titu...

### ISSUE THREAD

**Issue by door43app** [Door43/translationStudio2#258] opened 2015-02-06 18:48 UTC
Notes
======
closed when switching to titus

Environment
======
version: 2.0.3
build: 55
UDID: 4c0159756149d993
Android Release: 4.1.1
Androind SDK: 16
Brand: generic
Device: vbox86tp
Log history
======
2/6/15 6:47 PM [com.door43.translationstudio.projects.ProjectManager]:The notes were not found for project tit
eTranslations/tit/en/udb/notes.json

n

**Comment by neutrinog** [comment] 2015-02-06 18:52
this happened once when switching to obs as well

**Comment by neutrinog** [comment] 2015-02-06 18:54
saw this in a stack trace that seemed to have been archived automatically.
NumberFormatException invalid int "4-5".
VerseSpan line 27

**Comment by neutrinog** [comment] 2015-02-06 20:11
I'm pretty sure the problem is due to ram

**Comment by neutrinog** [comment] 2015-02-06 22:31
this is being closed as an issue that only occurs while the device is connected to adb.

**Closed by neutrinog** 2015-02-06 22:31 UTC
Labels: 2.0.3, bug report
