### ISSUE TITLE
Cannot find menu bar

### ISSUE THREAD

**Issue by melvilje** [Door43/translationStudio2#312] opened 2015-02-16 01:16 UTC
Cannot find the menu bar on recent releases of TranslationStudio. 
Current install is tS_2.1.1_build57.apk 
Device is Nexus 7
Android version 5.0.2
Kernel version 3.4.0-g154bef4

![ts-screen](https://cloud.githubusercontent.com/assets/10361022/6206078/124a2cda-b547-11e4-9126-6444255658fc.jpg)

**Comment by neutrinog** [comment] 2015-02-16 05:06
The normal menu bar is hidden when the translation input (right side of the screen) has been tapped. It is replaced with a new menu which at this point is empty except for Bible projects.
You can back out of the blue translation menu by closing all the side drawers (library and resources) and taping the left arrow in the menu.

I think probably returning to the normal menu when opening the library (or any other activity) would be a good default action.

Also, I believe the app incorrectly allows you to open the translation menu before a project has first been selected thus adding to the confusion.

**Comment by neutrinog** [comment] 2015-02-20 17:44
There should be a back arrow that closes the blue menu. 
https://www.evernote.com/shard/s18/sh/c86a2b31-cf21-4dd7-a5a3-dcb41fd69991/cc5888e9cba0ec578905c779e3601418

**Comment by neutrinog** [comment] 2015-02-20 18:00
Apparently the arrow is visible, but clicking on it does not close the menu.

**Comment by jag3773** [comment] 2015-02-24 00:31
Note that this is still a problem.  Do you have Android 5 to test with @neutrinog ?

**Comment by neutrinog** [comment] 2015-02-24 00:42
@jag3773 yes I tested it in a virtualized instance of a Nexus 7 with Android 5 and I was not able to reproduce the error. The only physical device I have is a galaxy s 2

**Comment by melvilje** [comment] 2015-02-24 00:58
What can be done on the tablet to provide more information about this ( apparently rare? ) anomaly?

**Comment by neutrinog** [comment] 2015-02-24 01:05
if you can get to the bug report window and submit a report from the app that would be great because that includes logs and other system information. However, if this problem exists from the moment the app starts that won't be possible. Otherwise, the easiest way would be to plug one of the error prone devices into my computer and manually debug it. I'd want to do some more research before pulling that card though because that's not entirely practical.

**Comment by melvilje** [comment] 2015-02-24 03:23
I've been advised to consult with Christine Jarka, who has the same tablet at the same os.

**Comment by melvilje** [comment] 2015-03-08 07:33
'Coaching' in the use of tS2 build 68 by another user did not uncover any customer errors. Build 71 does not initialize. It installs and opens, but after 'agreeing' to the 'terms of use', it types a series of messages ending with 'Launching translator' and then goes inactive. Reactivating it produces the same result. If it has any bearing, in an effort to trouble shoot the problem of not seeing the green menu bar, a change was made to the tablets 'Backup and reset' settings to not 'restore backed up settings and data' when the build was installed.

**Comment by ChrisJarka** [comment] 2015-03-27 20:19
Again another android (Nexus 7) is having the same issues. We have uninstalled and reinstalled the tS for 3 times - no luck.  Interesting - in GP there is no prompt for download just for install (makes me wonder if the tablet 'knows' there is a download available and that might be the issue.

**Comment by ChrisJarka** [comment] 2015-03-29 15:40
The above Nexus 7 has been reset - tS downloaded and installed - still opens with the verse bar and tapping on the back arrow does nothing. This Nexus belongs to Bruce Smith

**Comment by neutrinog** [comment] 2015-04-02 22:19
I believe this issue has finally been resolved! I'll leave this issue open until we're able to test on an actual device.

**Closed** 2015-04-03 00:15 UTC
Labels: bug, in review

**Comment by ChrisJarka** [comment] 2015-04-03 14:48
How will the user know? Will they need to delete the app and then reinstall?

**Comment by neutrinog** [comment] 2015-04-03 16:36
it will be available in the next update.
